theme = "hugo-paper"
baseURL = "http://example.org/"
languageCode = "en-us"
title = "Python Slides"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

slide_title = "Introduction to Python"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

[[menu.main]]
    name = "Resources"
    url = "/resources/"
    weight = 2